build=GNU\ ARM\ v10\.3\.1\ -\ Default

all:
	bear make -C $(build) -j12 all

flags:
	make -C $(build)

clean:
	make -C $(build) clean && rm -rf compile_commands.json

update:
	rm -rf $(build)/app.o $(build)/*.axf && make -C $(build) -j12 all

rebuild:
	$(MAKE) clean && $(MAKE) all

.PHONY: all clean flags update rebuild
